<?php
/**
 * Use this file to generate the map.json file. 
 * Set all mapping information here. format of mapping arrays is as shown below.
 * 'site-variable'=> array('app-variable-value'=>'site-specific-value')
 */
$mapping = array(
'ad[adtype_id]'=> array('rent'=>'1', 'want_to_rent'=>'2', 'services'=>'3', 'sale'=>'4', 'want_to_buy'=>'5'),

'ad[propertytype_id]'=> array('default_value'=>'25', 'common_room'=>'34', 'master_room'=>'35', 'Apartment or Condo'=>'38', 'Landed House'=>'7', 
	'Office'=>'2', 'company_guest_house'=>'3', 'conference_hall'=>'32',
	'exhibition_hall'=>'33', 'HDB Apartment'=>'48', 'other'=>'25', 'Land'=>'39'),

'ad[adcity_id]' => array("Admiralty"=>'88',	"Alexandra"=>'2',
						"Aljunied"=>'1',
						"Ang Mo Kio"=>'102',
						"Ayer Rajah"=>'3',
						"Balestier Road"=>'4',
						"Bedok"=>'70',
						"Bedok Reservoir"=>'71',
						"Benoi"=>'118',
						"Bishan"=>'5',
						"Boon Lay"=>'119',
						"Buangkok"=>'103',
						"Bugis"=>'6',
						"Bukit Batok"=>'120',
						"Bukit Chandu"=>'7',
						"Bukit Gombak"=>'121',
						"Bukit Ho Swee"=>'8',
						"Bukit Merah"=>'9',
						"Bukit Panjang"=>'122',
						"Bukit Timah"=>'10',
						"Buona Vista"=>'11',
						"Caldecott Hill"=>'12',
						"Central Area"=>'13',
						"Central Catchment"=>'89',
						"Chai Chee"=>'72',
						"Changi"=>'73',
						"changi Bay"=>'74',
						"Changi Eas"=>'75',
						"Changi Villag"=>'76',
						"Chinatown"=>'14',
						"Choa Chu Kang"=>'123',
						"Chong Pang"=>'90',
						"Clementi"=>'124',
						"Commonwealth"=>'15',
						"Defu"=>'104',
						"Dhoby Ghaut"=>'16',
						"Dover"=>'17',
						"East Coast"=>'77',
						"Emerald Hill"=>'18',
						"Esplanade"=>'19',
						"Eunos"=>'78',
						"Farrer Park"=>'20',
						"Geylang"=>'21',
						"Gul"=>'125',
						"HarbourFront"=>'22',
						"Hillview"=>'126',
						"Holland Village"=>'23',
						"Hougang"=>'105',
						"Jalan Besar"=>'24',
						"Jalan Kayu"=>'106',
						"Joo Chiat"=>'25',
						"Joo Koon"=>'127',
						"Jurong East"=>'128',
						"Jurong West"=>'128',
						"Kaki Bukit"=>'79',
						"Kallang or Whampoa"=>'26',
						"Kampong Glam"=>'27',
						"Katong"=>'28',
						"Kebun Baru"=>'107',
						"Kembangan"=>'80',
						"Kent Ridge"=>'29',
						"Kim Seng"=>'31',
						"Kolam Ayer"=>'30',
						"Kranji"=>'91',
						"Lim Chu Kang"=>'92',
						"Little India"=>'32',
						"Lorong Chuan"=>'108',
						"Lorong Halus"=>'109',
						"Loyang"=>'81',
						"MacPherson"=>'33',
						"Mandai"=>'93',
						"Marina Bay"=>'34',
						"Marina Centre"=>'35',
						"Marina East"=>'36',
						"Marina South"=>'37',
						"Marine Parade"=>'38',
						"Marsiling"=>'94',
						"Marymount"=>'39',
						"Mount Faber"=>'41',
						"Mount Vernon"=>'42',
						"Mountbatten"=>'40',
						"Murai"=>'129',
						"Museum"=>'43',
						"Nanyang"=>'130',
						"Neo Tiew"=>'95',
						"Newton"=>'44',
						"North Eastern Islands"=>'110',
						"Novena"=>'45',
						"One North"=>'46',
						"Orchard Road"=>'47',
						"Outram"=>'48',
						"Pandan"=>'131',
						"Pasir Laba"=>'132',
						"Pasir Panjang"=>'49',
						"Pasir Ris"=>'82',
						"Paya Lebar"=>'83',
						"Pioneer"=>'133',
						"Potong Pasir"=>'50',
						"Punggol"=>'111',
						"Queenstown"=>'52',
						"Radin Mas"=>'53',
						"Raffles Place"=>'54',
						"Rochor"=>'51',
						"Sarimbun"=>'134',
						"Seletar"=>'112',
						"Sembawang"=>'96',
						"Sengkang"=>'113',
						"Senoko"=>'97',
						"Serangoon"=>'114',
						"Serangoon Gardens"=>'115',
						"Serangoon North"=>'116',
						"Shenton Way"=>'55',
						"Siglap"=>'84',
						"Simei"=>'85',
						"Simpang"=>'98',
						"Sin Ming"=>'56',
						"Singapore River"=>'57',
						"Southern Islands"=>'58',
						"St Michaels"=>'59',
						"Sungei Kadut"=>'99',
						"Taman Jurong"=>'135',
						"Tampines"=>'86',
						"Tanah Merah"=>'87',
						"Tanglin"=>'62',
						"Tanjong Pagar"=>'60',
						"Tanjong Rhu"=>'61',
						"Teban Gardens"=>'136',
						"Telok Ayer"=>'63',
						"Telok Blangah"=>'64',
						"Tengah"=>'137',
						"Thomson"=>'65',
						"Tiong Bahru"=>'66',
						"Toa Payoh"=>'67',
						"Toh Tuck"=>'138',
						"Tuas"=>'139',
						"Ubi"=>'68',
						"West Coast"=>'140',
						"Western Islands"=>'141',
						"Western Water"=>'142',
						"Whampoa"=>'69',
						"Woodlands"=>'100',
						"Yew Tee"=>'143',
						"Yio Chu Kang"=>'117',
						"Yishun"=>'101'),

'ad[mrtstation_id]' => array(''=>'', 'Admiralty_NS10'=>'152'),

'ad[lrt_id]' => array(''=>'', 'Bakau'=>'19'),

'ad[district_id]' => array('default_value'=>'24',
						'Unassigned'=>'0',
						"Boat Quay or Raffles Place"=>'1',   
						"Chinatown or Tanjong Pagar"=>'2',		
						"Alexandra or Commonwealth"=>'3',       
						"Harbourfrount or Telok Blangah"=>'4',  
						"Buona Vista or West Coast"=>'5',       
						"City Hall or Clarke Quay"=>'0',   //TODO: this value is not present in rentinsingapore    
						"Beach Road or Bugis or Rochor"=>'6',       
						"Farrer Park or Serangoon"=>'10',      
						"Orchard or River Valley"=>'9',    
						"Tanglin or Holland"=>'10',
						"Newton or Novena"=>'11',
						"Balestier or Toa Payoh"=>'12',
						"Macpherson or Potong Pasir"=>'13',
						"Eunos or Geylang or Paya Lebar"=>'14',
						"East Coast or Marine Parade"=>'15',
						"Bedok or Upper East Coast"=>'16',
						"Changi Airport or Changi Village"=>'17',
						"Pasir Ris or Tampines"=>'18',
						"Hougang or Ponggol or Sengkang"=>'19',
						"Ang Mo Kio or Bishan or Thomson"=>'20',
						"Clementi or Upper Bukit Timah"=>'21',
						"Boon Lay or Jurong or Tuas"=>'22',
						"Bukit Batok or Bukit Panjang"=>'23',
						"Choa Chu Kang or Tengah"=>'23',
						"Admiralty or Woodlands"=>'25',
						"Mandai or Upper Thomson"=>'26',
						"Sembawang or Yishun"=>'27',
						"Seletar or Yio Chu Kang"=>'28'),

'ad[mycountry_id]' => array('default_value'=>'0', "Indian"=>'100', "American"=>'222', "chinese"=>'46',"malay"=>'150', "other"=>'0'),

'ad[train_station]' => array('1'=>'1', '0'=>'0'),
'ad[swimming_pool]' => array('1'=>'1', '0'=>'0'),
'ad[lowfloor]' => array('1'=>'1', '0'=>'0'),
'ad[highfloor]' => array('1'=>'1', '0'=>'0'),
'ad[excercise]' => array('1'=>'1', '0'=>'0'),
'ad[tennis]' => array('1'=>'1', '0'=>'0'),
'ad[spa]' => array('1'=>'1', '0'=>'0'),
'ad[internet]' => array('1'=>'1', '0'=>'0'),
'ad[aircon]' => array('1'=>'1', '0'=>'0'),
'ad[pub]' => array('1'=>'1', '0'=>'0')
);

file_put_contents('map.json',json_encode($mapping));
?>